CREATE OR REPLACE TABLE SOCCER_INTEL.CURATED.CURRENT_LEAGUE_STATUS (
    LEAGUE_ID NUMBER,
    LEAGUE_NAME STRING,
    SEASON NUMBER,
    STATUS_CATEGORY STRING,
    API_STATUS STRING,
    API_WARNING STRING,
    LATEST_IDEMPOTENCY_KEY STRING,
    LATEST_REQUEST_KEY STRING,
    LATEST_CORRELATION_ID STRING,
    LATEST_FETCHED_AT_UTC TIMESTAMP_NTZ,
    LATEST_INGESTED_AT_UTC TIMESTAMP_NTZ,
    EVENT_DATE DATE,
    LATEST_PAYLOAD_JSON STRING
);

