USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS SOCCERINTEL_STAGING_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS SOCCERINTEL_STAGING;

CREATE SCHEMA IF NOT EXISTS SOCCERINTEL_STAGING.GOLD;

CREATE ROLE IF NOT EXISTS SOCCERINTEL_STAGING_ROLE;

GRANT USAGE ON WAREHOUSE SOCCERINTEL_STAGING_WH
    TO ROLE SOCCERINTEL_STAGING_ROLE;

GRANT USAGE ON DATABASE SOCCERINTEL_STAGING
    TO ROLE SOCCERINTEL_STAGING_ROLE;

GRANT USAGE ON SCHEMA SOCCERINTEL_STAGING.GOLD
    TO ROLE SOCCERINTEL_STAGING_ROLE;

GRANT CREATE TABLE ON SCHEMA SOCCERINTEL_STAGING.GOLD
    TO ROLE SOCCERINTEL_STAGING_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN SCHEMA SOCCERINTEL_STAGING.GOLD
    TO ROLE SOCCERINTEL_STAGING_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA SOCCERINTEL_STAGING.GOLD
    TO ROLE SOCCERINTEL_STAGING_ROLE;

CREATE USER IF NOT EXISTS SVC_SOCCERINTEL_DATABRICKS
    TYPE = SERVICE
    DEFAULT_ROLE = SOCCERINTEL_STAGING_ROLE
    DEFAULT_WAREHOUSE = SOCCERINTEL_STAGING_WH
    DEFAULT_NAMESPACE = SOCCERINTEL_STAGING.GOLD
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service user for Databricks Gold-to-Snowflake publication';

GRANT ROLE SOCCERINTEL_STAGING_ROLE
    TO USER SVC_SOCCERINTEL_DATABRICKS;

-- Render this template locally or in CI by replacing <SNOWFLAKE_RSA_PUBLIC_KEY>
-- with the public key body only.
-- Do not commit rendered SQL containing environment-specific key material.
ALTER USER SVC_SOCCERINTEL_DATABRICKS
    SET RSA_PUBLIC_KEY = '<SNOWFLAKE_RSA_PUBLIC_KEY>';

CREATE OR REPLACE TABLE SOCCERINTEL_STAGING.GOLD.CURRENT_LEAGUE_STATUS (
    LEAGUE_ID NUMBER,
    LEAGUE_NAME STRING,
    SEASON NUMBER,
    API_STATUS STRING,
    API_RESPONSE_LENGTH NUMBER,
    API_WARNING STRING,
    STATUS_CATEGORY STRING,
    LATEST_IDEMPOTENCY_KEY STRING,
    LATEST_REQUEST_KEY STRING,
    LATEST_CORRELATION_ID STRING,
    LATEST_FETCHED_AT_UTC TIMESTAMP_NTZ,
    LATEST_INGESTED_AT_UTC TIMESTAMP_NTZ,
    EVENT_DATE DATE,
    LATEST_PAYLOAD_JSON STRING
);
